window.HELIX = {
  user: "algorathem",
  host: "helix",
  distro: "Helix OS",
  kernel: "6.11.0-helix",
  de: "Hyprfolio",
  shell: "zsh 5.9",
  location: "Singapore · NTU",
  title: "builder of tools, classrooms, and strange machines",
  github: "https://github.com/algorathem",
  avatar: "https://avatars.githubusercontent.com/u/166614632?v=4",
  email: "",
  bio: [
    "Engineering student at Nanyang Technological University.",
    "I ship full-stack products on Cloudflare and Vercel, teach with software, and keep a hardware bench nearby — FPGA, Arduino, CAD, the occasional Unity world.",
    "This desktop is the portfolio. Open the apps, or just type.",
  ],
  projects: [
    {
      id: "inspectlab",
      name: "InspectLab",
      tag: "education",
      year: "2026",
      blurb: "Interactive academy for web scraping. Paste a public URL, inspect live markup, extract a table, and copy working Python, Node, or DevTools code aimed at that page.",
      stack: ["React", "Vite", "Workers", "D1"],
      href: "https://inspectlab.kcleck06.workers.dev",
      repo: "",
    },
    {
      id: "stickeredu",
      name: "stickerEDU.ai",
      tag: "edtech",
      year: "2026",
      blurb: "Classroom platform: one class code, Gemini-built weekly picture books, sticker rewards, Lexile-style reports, and a hedgehog mascot that coaches reading aloud.",
      stack: ["React", "Hono", "Neon", "R2", "Gemini"],
      href: "",
      repo: "https://github.com/algorathem/stickeredu",
    },
    {
      id: "shoppilot",
      name: "ShopPilot",
      tag: "agents",
      year: "2026",
      blurb: "Multi-turn shopping copilot for TechJam. Hybrid FTS + dense retrieval on a frozen 50k catalog. Hit@10 0.975, MRR 0.872, no required LLM on the scoring path.",
      stack: ["Python", "SQLite FTS5", "retrieval"],
      href: "",
      repo: "https://github.com/algorathem/techjam2026-shopping-copilot",
    },
    {
      id: "caretrail",
      name: "CareTrail",
      tag: "product",
      year: "2026",
      blurb: "Ticket marketplace for student-led tours with elders and children. Friendliness ratings, Stripe Connect payouts, Neon Postgres, content moderation.",
      stack: ["Next.js", "Stripe", "Neon", "Vercel"],
      href: "",
      repo: "",
    },
    {
      id: "threebody",
      name: "Three Body",
      tag: "game",
      year: "2026",
      blurb: "Playable reconstruction of the VR game from Liu Cixin's novel: three suns, Stable and Chaotic Eras, dehydration, and the great human computer.",
      stack: ["HTML", "Canvas", "physics"],
      href: "https://three-body-trisolaris.netlify.app",
      repo: "",
    },
    {
      id: "journal",
      name: "Trading Chart Journal",
      tag: "privacy",
      year: "2026",
      blurb: "Zero-knowledge chart journal. Screenshots, notes, and reflections are encrypted in the browser before they ever touch D1 or R2.",
      stack: ["Workers", "D1", "R2", "AES-GCM"],
      href: "",
      repo: "",
    },
    {
      id: "zylar",
      name: "Zylar's World",
      tag: "game",
      year: "2025",
      blurb: "Unity WebGL world. A separate build from this desktop — still living on the local machine like a forgotten /opt game.",
      stack: ["Unity", "WebGL"],
      href: "",
      repo: "",
    },
  ],
  skills: [
    { group: "languages", items: ["Python", "TypeScript", "JavaScript", "SQL", "HTML/CSS"] },
    { group: "web & agents", items: ["React", "Next.js", "Vite", "Hono", "Workers", "retrieval"] },
    { group: "data & cloud", items: ["Postgres / Neon", "D1", "R2", "Stripe", "Docker"] },
    { group: "hardware", items: ["FPGA / Vivado", "Arduino", "Fusion 360", "Blender"] },
    { group: "other", items: ["Linux / Kali", "Unity", "game systems", "teaching tools"] },
  ],
  fortunes: [
    "The best rice is the one you can still compile.",
    "cat README.md is a valid first impression.",
    "If it works in Hyprland, it works in the portfolio.",
    "sudo make me a sandwich — permission denied, make it yourself.",
    "Uptime is a love language.",
    "There is no cloud, only someone else's computer. This one is yours.",
    "A window manager is just a to-do list with shadows.",
    "ntu-helix: where labs, Workers, and late-night terminals meet.",
  ],
};
